
// This file is automatically generated. Do not modify it manually.
// For more information, see https://firebase.google.com/docs/build/manage-web-apps
export const firebaseConfig = {
  "projectId": "studio-7586859725-d60db",
  "appId": "1:293455856929:web:8910371fe6488f4fcf6a60",
  "apiKey": "AIzaSyAcTbcYDNLfYEboF33GPgklspxtWSE_IAQ",
  "authDomain": "studio-7586859725-d60db.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "293455856929"
};
